### ISSUE TITLE
Implement tests

### ISSUE THREAD

**Issue by foo2810** [foo2810/ad-hoc-vimconfig#3]
Test some implemented functions

**Points**
- [x] Test comment toggle function
- [x] Test trim trailing spaces (#10 )
- [x] Check dependencies to vim versions (#11 )
  - whether or not a builtin function or a command used in scripts work in older version (e.g. vim v7.0 ~)
- [x] Test on CI process (#7 )

**Comment by foo2810** [comment]
Implement testing toggle comments:  99c82a0f47f5eae2b8844ae587e447c4d316d8f3

merged this patch to origin/main

**Comment by foo2810** [comment]
Note: implements this issue on [issue-3](https://github.com/foo2810/ad-hoc-vimconfig/tree/issue-3) and [ci_test](https://github.com/foo2810/ad-hoc-vimconfig/tree/ci_test)

**Comment by foo2810** [comment]
Test script for toggle comment may fail in vim v7.3 or older.

This problem have been handled in #9 .

**Comment by foo2810** [comment]
Implements for test trim trailing spaces in #10

**Comment by foo2810** [comment]
So far, all necessary tests have been conducted (maybe...).
